/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panel;

import DataFile.Book;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ListBook extends javax.swing.JPanel {

    /**
     * Creates new form ListAdmin
     */
    public ListBook() {
        initComponents();
        //AddRowsToTable();
        //reset();
    }

    public void AddRowsToTable() {
        resetTable();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Object[] rowData = new Object[7];

        ArrayList<Book> book = new Book().ListAllBooks();

        for (Book a : book) {
            rowData[0] = a.getIDBook();
            rowData[1] = a.getNameBook();
            rowData[2] = a.Author.getNamePublisher();
            String DOB[] = a.Author.getDOPublisher().split("#");
            rowData[3] = DOB[2] + "/" + DOB[1] + "/" + DOB[0];
            rowData[4] = a.getNoOfBooks();
            rowData[5] = a.Reciever.getName();
            rowData[6] = a.getSalary();
            model.addRow(rowData);
        }
    }

    /*
            String DOB[] = a.Author.getDOPublisher().split("#");
            rowData[3] = DOB[2] + "/" + DOB[1] + "/" + DOB[0];
            rowData[3] = a.Author.getDOPublisher();
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDBook", "NameBook", "Publisher", "DOPPublisher", "NoOfBook", "Reciever", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void resetTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            while (jTable1.getRowCount() > 0) {
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    model.removeRow(i);
                }
            }
            model.removeRow(0);
        } catch (Exception e) {
            ;
        }
    }
}
