/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panel;

import DataFile.Client;
import Safety.Validation;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class SearchClient extends javax.swing.JPanel {

    /**
     * Creates new form SearchAdmin
     */
    public SearchClient() {
        initComponents();
        visable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWrongPassword = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelWrongPhoneNo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelWrongAddress = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabelSuccessOrFail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearchKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jPanelSearch = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jPanelreset = new javax.swing.JPanel();
        jLabelReset = new javax.swing.JLabel();
        jPanelRemove = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelUpdate = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelWronguserName1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelWronguserName2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelwrongEmail = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelWrongPassword1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelWrongPhoneNo1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelWrongAddress1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jPanelWrongID = new javax.swing.JPanel();
        jLabelWronguserName3 = new javax.swing.JLabel();

        jPanelWrongPassword.setBackground(new java.awt.Color(105, 105, 105));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel10.setText("Wrong Password");

        javax.swing.GroupLayout jPanelWrongPasswordLayout = new javax.swing.GroupLayout(jPanelWrongPassword);
        jPanelWrongPassword.setLayout(jPanelWrongPasswordLayout);
        jPanelWrongPasswordLayout.setHorizontalGroup(
            jPanelWrongPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelWrongPasswordLayout.setVerticalGroup(
            jPanelWrongPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongPhoneNo.setBackground(new java.awt.Color(105, 105, 105));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel12.setText("Wrong Phone No");

        javax.swing.GroupLayout jPanelWrongPhoneNoLayout = new javax.swing.GroupLayout(jPanelWrongPhoneNo);
        jPanelWrongPhoneNo.setLayout(jPanelWrongPhoneNoLayout);
        jPanelWrongPhoneNoLayout.setHorizontalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongPhoneNoLayout.setVerticalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongAddress.setBackground(new java.awt.Color(105, 105, 105));

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel16.setText("Wrong Address");

        javax.swing.GroupLayout jPanelWrongAddressLayout = new javax.swing.GroupLayout(jPanelWrongAddress);
        jPanelWrongAddress.setLayout(jPanelWrongAddressLayout);
        jPanelWrongAddressLayout.setHorizontalGroup(
            jPanelWrongAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelWrongAddressLayout.setVerticalGroup(
            jPanelWrongAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setBackground(new java.awt.Color(105, 105, 105));

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Search For Client ...!");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Client ID");

        jTextFieldSearchKey.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTextFieldSearchKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSearchKey.setBorder(null);
        jTextFieldSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchKeyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");

        jTextFieldUserName.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUserName.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");

        jTextFieldEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setBorder(null);

        jTextFieldPassword.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTextFieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPassword.setBorder(null);

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTextFieldPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNumber.setBorder(null);

        jTextFieldAddress.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTextFieldAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAddress.setBorder(null);

        jPanelSearch.setBackground(new java.awt.Color(105, 105, 105));
        jPanelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSearchMouseExited(evt);
            }
        });

        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search_48px.png"))); // NOI18N
        jLabelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearch)
                .addGap(10, 10, 10))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearch)
                .addContainerGap())
        );

        jPanelreset.setBackground(new java.awt.Color(105, 105, 105));
        jPanelreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelresetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelresetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelresetMouseExited(evt);
            }
        });

        jLabelReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_48px.png"))); // NOI18N
        jLabelReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelresetLayout = new javax.swing.GroupLayout(jPanelreset);
        jPanelreset.setLayout(jPanelresetLayout);
        jPanelresetLayout.setHorizontalGroup(
            jPanelresetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelresetLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelReset)
                .addGap(10, 10, 10))
        );
        jPanelresetLayout.setVerticalGroup(
            jPanelresetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelresetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReset)
                .addContainerGap())
        );

        jPanelRemove.setBackground(new java.awt.Color(105, 105, 105));
        jPanelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Trash_48px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelRemoveLayout = new javax.swing.GroupLayout(jPanelRemove);
        jPanelRemove.setLayout(jPanelRemoveLayout);
        jPanelRemoveLayout.setHorizontalGroup(
            jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemoveLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(10, 10, 10))
        );
        jPanelRemoveLayout.setVerticalGroup(
            jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(10, 10, 10))
        );

        jPanelUpdate.setBackground(new java.awt.Color(105, 105, 105));
        jPanelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelUpdateMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Available_Updates_48px_3.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdateLayout = new javax.swing.GroupLayout(jPanelUpdate);
        jPanelUpdate.setLayout(jPanelUpdateLayout);
        jPanelUpdateLayout.setHorizontalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanelUpdateLayout.setVerticalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(105, 105, 105));

        jLabelWronguserName1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabelWronguserName1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWronguserName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWronguserName1.setText("wrong ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWronguserName1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelWronguserName1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(105, 105, 105));

        jLabelWronguserName2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabelWronguserName2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWronguserName2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWronguserName2.setText("wrong username");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWronguserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabelWronguserName2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(105, 105, 105));

        jLabelwrongEmail.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabelwrongEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelwrongEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelwrongEmail.setText("wrong Email");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelwrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelwrongEmail))
        );

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Search");

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Reset");

        jPanelWrongPassword1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel11.setText("Wrong Password");

        javax.swing.GroupLayout jPanelWrongPassword1Layout = new javax.swing.GroupLayout(jPanelWrongPassword1);
        jPanelWrongPassword1.setLayout(jPanelWrongPassword1Layout);
        jPanelWrongPassword1Layout.setHorizontalGroup(
            jPanelWrongPassword1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongPassword1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelWrongPassword1Layout.setVerticalGroup(
            jPanelWrongPassword1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongPassword1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanelWrongPhoneNo1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel15.setText("Wrong Phone No");

        javax.swing.GroupLayout jPanelWrongPhoneNo1Layout = new javax.swing.GroupLayout(jPanelWrongPhoneNo1);
        jPanelWrongPhoneNo1.setLayout(jPanelWrongPhoneNo1Layout);
        jPanelWrongPhoneNo1Layout.setHorizontalGroup(
            jPanelWrongPhoneNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongPhoneNo1Layout.setVerticalGroup(
            jPanelWrongPhoneNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongAddress1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel17.setText("Wrong Address");

        javax.swing.GroupLayout jPanelWrongAddress1Layout = new javax.swing.GroupLayout(jPanelWrongAddress1);
        jPanelWrongAddress1.setLayout(jPanelWrongAddress1Layout);
        jPanelWrongAddress1Layout.setHorizontalGroup(
            jPanelWrongAddress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAddress1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelWrongAddress1Layout.setVerticalGroup(
            jPanelWrongAddress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Delete");

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("UPdate");

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Client ID");

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jPanelWrongID.setBackground(new java.awt.Color(105, 105, 105));

        jLabelWronguserName3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabelWronguserName3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWronguserName3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWronguserName3.setText("wrong ID");

        javax.swing.GroupLayout jPanelWrongIDLayout = new javax.swing.GroupLayout(jPanelWrongID);
        jPanelWrongID.setLayout(jPanelWrongIDLayout);
        jPanelWrongIDLayout.setHorizontalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWronguserName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongIDLayout.setVerticalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelWronguserName3)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongPhoneNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanelWrongID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, 0))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSuccessOrFail)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelWrongPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongPhoneNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelWrongAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseClicked
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_jLabelSearchMouseClicked

    private void jLabelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseEntered
        // TODO add your handling code here:
        setColor(jPanelSearch);
    }//GEN-LAST:event_jLabelSearchMouseEntered

    private void jLabelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseExited
        // TODO add your handling code here:
        getColor(jPanelSearch);
    }//GEN-LAST:event_jLabelSearchMouseExited

    private void jPanelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchMouseClicked
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_jPanelSearchMouseClicked

    private void jPanelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchMouseEntered
        // TODO add your handling code here:
        setColor(jPanelSearch);
    }//GEN-LAST:event_jPanelSearchMouseEntered

    private void jPanelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchMouseExited
        // TODO add your handling code here:
        getColor(jPanelSearch);
    }//GEN-LAST:event_jPanelSearchMouseExited

    private void jLabelResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseClicked
        // TODO add your handling code here:

        resetPanel();
    }//GEN-LAST:event_jLabelResetMouseClicked

    private void jLabelResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseEntered
        // TODO add your handling code here:
        setColor(jPanelreset);
    }//GEN-LAST:event_jLabelResetMouseEntered

    private void jLabelResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseExited
        // TODO add your handling code here:
        getColor(jPanelreset);
    }//GEN-LAST:event_jLabelResetMouseExited

    private void jPanelresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelresetMouseClicked
        // TODO add your handling code here:

        resetPanel();
    }//GEN-LAST:event_jPanelresetMouseClicked

    private void jPanelresetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelresetMouseEntered
        // TODO add your handling code here:
        setColor(jPanelreset);
    }//GEN-LAST:event_jPanelresetMouseEntered

    private void jPanelresetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelresetMouseExited
        // TODO add your handling code here:
        getColor(jPanelreset);
    }//GEN-LAST:event_jPanelresetMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Remove();

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        setColor(jPanelRemove);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        getColor(jPanelRemove);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jPanelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseClicked
        // TODO add your handling code here:
        Remove();
    }//GEN-LAST:event_jPanelRemoveMouseClicked

    private void jPanelRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseEntered
        // TODO add your handling code here:
        setColor(jPanelRemove);
    }//GEN-LAST:event_jPanelRemoveMouseEntered

    private void jPanelRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseExited
        // TODO add your handling code here:
        getColor(jPanelRemove);
    }//GEN-LAST:event_jPanelRemoveMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        setColor(jPanelUpdate);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        getColor(jPanelUpdate);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jPanelUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUpdateMouseClicked
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_jPanelUpdateMouseClicked

    private void jPanelUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUpdateMouseEntered
        // TODO add your handling code here:
        setColor(jPanelUpdate);
    }//GEN-LAST:event_jPanelUpdateMouseEntered
    public void resetPanel() {
        full();
        jTextFieldAddress.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPassword.setText("");
        jTextFieldPhoneNumber.setText("");
        jTextFieldUserName.setText("");
        jTextFieldSearchKey.setText("");
        jLabelSuccessOrFail.setText("Search For Client ...!");
        visable();
        Frist_Half();

    }

    public void setPanel(Client a) {
        jTextFieldID.setText(String.valueOf(a.getID()));
        jTextFieldAddress.setText(a.getAddress());
        jTextFieldEmail.setText(a.getEmail());
        jTextFieldPassword.setText(a.getPass());
        jTextFieldPhoneNumber.setText(a.getPhoneNo());
        jTextFieldUserName.setText(a.getUserName());
    }
    private void jPanelUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUpdateMouseExited
        // TODO add your handling code here:
        getColor(jPanelUpdate);
    }//GEN-LAST:event_jPanelUpdateMouseExited

    private void jTextFieldSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchKeyActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void setColor(JPanel p) {
        p.setBackground(new Color(0, 64, 128));
    }

    private void getColor(JPanel p) {
        p.setBackground(new Color(105, 105, 105));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelReset;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JLabel jLabelWronguserName1;
    private javax.swing.JLabel jLabelWronguserName2;
    private javax.swing.JLabel jLabelWronguserName3;
    private javax.swing.JLabel jLabelwrongEmail;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelRemove;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelUpdate;
    private javax.swing.JPanel jPanelWrongAddress;
    private javax.swing.JPanel jPanelWrongAddress1;
    private javax.swing.JPanel jPanelWrongID;
    private javax.swing.JPanel jPanelWrongPassword;
    private javax.swing.JPanel jPanelWrongPassword1;
    private javax.swing.JPanel jPanelWrongPhoneNo;
    private javax.swing.JPanel jPanelWrongPhoneNo1;
    private javax.swing.JPanel jPanelreset;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldSearchKey;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables

    private void Update() {
        Frist_Half();
        visable();
        if (!jTextFieldAddress.getText().equals("") && !jTextFieldEmail.getText().equals("") && !jTextFieldPassword.getText().equals("")
                && !jTextFieldPhoneNumber.getText().equals("") && !jTextFieldUserName.getText().equals("") && !jTextFieldSearchKey.getText().equals("")) {
            //All Check ...
            Validation v = new Validation();
            if (v.checkID(jTextFieldSearchKey.getText())) {
                if (v.checkName(jTextFieldUserName.getText())) {
                    if (v.checkPass(jTextFieldPassword.getText())) {
                        if (v.checkEmail(jTextFieldEmail.getText())) {
                            if (v.checkPhoneNo(jTextFieldPhoneNumber.getText())) {
                                Client a = new Client();
                                second_Half();
                                if (!jTextFieldID.getText().equals(jTextFieldSearchKey.getText())) {
                                    if (!a.Dublicate(Integer.parseInt(jTextFieldID.getText()))) {
                                        a = (Client) a.get(Integer.parseInt(jTextFieldSearchKey.getText()));
                                        if (a != null) {
                                            a.setID(Integer.parseInt(jTextFieldID.getText()));
                                            a.setAddress(jTextFieldAddress.getText());
                                            a.setEmail(jTextFieldEmail.getText());
                                            a.setPass(jTextFieldPassword.getText());
                                            a.setPhoneNo(jTextFieldPhoneNumber.getText());
                                            a.setUserName(jTextFieldUserName.getText());
                                            if (a.Edit(Integer.parseInt(jTextFieldSearchKey.getText()))) {
                                                resetPanel();
                                                jLabelSuccessOrFail.setText("Successfully Updated ...! :)");
                                            } else {
                                                jLabelSuccessOrFail.setText("error in Updated ...! :(");
                                            }
                                        } else {
                                            jLabelSuccessOrFail.setText("Not Found Client ...! Please, Enter Correct ID ...! :( ");

                                        }
                                        //End Start & start elses for Check
                                    } else {
                                        jLabelSuccessOrFail.setText("Not Allowed New Employee ID ");
                                        jPanelWrongID.setVisible(true);
                                        JOptionPane.showMessageDialog(null, "Not Allowed  Admin ID, Admin  ID is used. Please Try Again.");
                                        second_Half();
                                    }
                                } else {
                                    a = (Client) a.get(Integer.parseInt(jTextFieldSearchKey.getText()));
                                    if (a != null) {
                                        a.setID(Integer.parseInt(jTextFieldID.getText()));
                                        a.setAddress(jTextFieldAddress.getText());
                                        a.setEmail(jTextFieldEmail.getText());
                                        a.setPass(jTextFieldPassword.getText());
                                        a.setPhoneNo(jTextFieldPhoneNumber.getText());
                                        a.setUserName(jTextFieldUserName.getText());
                                        if (a.Edit(Integer.parseInt(jTextFieldSearchKey.getText()))) {
                                            resetPanel();
                                            jLabelSuccessOrFail.setText("Successfully Updated ...! :)");
                                        } else {
                                            jLabelSuccessOrFail.setText("error in Updated ...! :(");
                                        }
                                    } else {
                                        jLabelSuccessOrFail.setText("Not Found Client ...! Please, Enter Correct ID ...! :( ");

                                    }
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                                jPanelWrongPhoneNo.setVisible(true);
                                second_Half();
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again :(");
                            jPanel6.setVisible(true);
                            second_Half();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                        jPanelWrongPassword1.setVisible(true);
                        second_Half();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Not valid User Name Try Again :(");
                    jPanel5.setVisible(true);
                    second_Half();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Not valid ID Client Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanel4.setVisible(true);
                second_Half();
            }
        } else {
            jLabelSuccessOrFail.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
            second_Half();
        }

    }

    private void Remove() {
        visable();
        Frist_Half();
        if (!jTextFieldSearchKey.getText().equals("")) {
            if (new Validation().checkID(jTextFieldSearchKey.getText())) {
                Client a = new Client();
                second_Half();
                a = (Client) a.get(Integer.parseInt(jTextFieldSearchKey.getText()));
                if (a != null) {
                    a.Remove(Integer.parseInt(jTextFieldSearchKey.getText()));
                    jLabelSuccessOrFail.setText("Removed Successfully ...! :)");
                    resetPanel();
                } else {
                    jLabelSuccessOrFail.setText("Failed Removed ...! :(");
                    jPanel4.setVisible(true);
                    Frist_Half();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Not valid ID Client Try Again :(\nHint: ID Client Length should more than 4 .. ;)");
                jPanel4.setVisible(true);
                Frist_Half();
            }
        } else {
            jLabelSuccessOrFail.setText("Missing Required ID Client ... !  Please, complete it before submit ...! :(");
            Frist_Half();

        }

    }

    private void Search() {
        visable();
        Frist_Half();
        if (!jTextFieldSearchKey.getText().equals("")) {
            if (new Validation().checkID(jTextFieldSearchKey.getText())) {
                Client a = new Client();
                second_Half();
                a = (Client) a.get(Integer.parseInt(jTextFieldSearchKey.getText()));
                if (a != null) {
                    jLabelSuccessOrFail.setText("Founded ...! :) ");
                    setPanel(a);
                } else {
                    jLabelSuccessOrFail.setText("Not Found ...! :( ");
                    jPanel4.setVisible(true);

                    Frist_Half();
                }
            } else {
                jLabelSuccessOrFail.setText("Not valid ID Admin :( ");
                JOptionPane.showMessageDialog(null, "Not valid ID Client Try Again :(\nHint: ID Client Length should more than 4 .. ;)");
                jPanel4.setVisible(true);
                Frist_Half();
            }
        } else {
            jLabelSuccessOrFail.setText("Missing Required ID ... !  Please, complete it before submit ...! :(");
            Frist_Half();
        }

    }

    private void Frist_Half() {
        jTextFieldSearchKey.setEditable(true);
        jTextFieldUserName.setEditable(false);
        jTextFieldEmail.setEditable(false);

        jTextFieldPhoneNumber.setEditable(false);
        jTextFieldPassword.setEditable(false);
        jTextFieldAddress.setEditable(false);

    }

    private void second_Half() {
        jTextFieldSearchKey.setEditable(false);
        jTextFieldUserName.setEditable(true);
        jTextFieldEmail.setEditable(true);

        jTextFieldPhoneNumber.setEditable(true);
        jTextFieldPassword.setEditable(true);
        jTextFieldAddress.setEditable(true);
    }

    private void full() {
        jTextFieldSearchKey.setEditable(true);
        jTextFieldUserName.setEditable(true);
        jTextFieldEmail.setEditable(true);

        jTextFieldPhoneNumber.setEditable(true);
        jTextFieldPassword.setEditable(true);
        jTextFieldAddress.setEditable(true);
    }

    private void visable() {
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanelWrongAddress1.setVisible(false);
        jPanelWrongPassword1.setVisible(false);
        jPanelWrongPhoneNo1.setVisible(false);
        jPanelWrongID.setVisible(false);
    }
}
