/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panel;

import DataFile.Admin;
import DataFile.Employee;
import Safety.Validation;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Color;

/**
 *
 * @author DELL
 */
public class SearchEmployee extends javax.swing.JPanel {

    /**
     * Creates new form SearchAdmin
     */
    public SearchEmployee() {
        initComponents();
        editFalse();
        visable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWrongUserName = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanelWrongName = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanelWrongPassword = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanelWrongEmail = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanelWrongOfficeHours = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmployeeName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldOfficeHour = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldSearchKey = new javax.swing.JTextField();
        jPanelSearch = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jPanelreset = new javax.swing.JPanel();
        jLabelReset = new javax.swing.JLabel();
        jPanelRemove = new javax.swing.JPanel();
        jLabelRemove = new javax.swing.JLabel();
        jPanelUpdate = new javax.swing.JPanel();
        jLabelUpdate = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelWrongUserName1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanelWrongName1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanelWrongPassword1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanelWrongEmail1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanelWrongPhoneNo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanelWrongAddress = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanelWrongOfficeHours1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelWrongName2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jPanelWrongName3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jPanelWrongUserName.setBackground(new java.awt.Color(105, 105, 105));

        jLabel36.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel36.setText("Wrong User Name");

        javax.swing.GroupLayout jPanelWrongUserNameLayout = new javax.swing.GroupLayout(jPanelWrongUserName);
        jPanelWrongUserName.setLayout(jPanelWrongUserNameLayout);
        jPanelWrongUserNameLayout.setHorizontalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        jPanelWrongUserNameLayout.setVerticalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongName.setBackground(new java.awt.Color(105, 105, 105));

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel19.setText("Wrong Name");

        javax.swing.GroupLayout jPanelWrongNameLayout = new javax.swing.GroupLayout(jPanelWrongName);
        jPanelWrongName.setLayout(jPanelWrongNameLayout);
        jPanelWrongNameLayout.setHorizontalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongNameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWrongNameLayout.setVerticalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19)
        );

        jPanelWrongPassword.setBackground(new java.awt.Color(105, 105, 105));

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel20.setText("Wrong Password");

        javax.swing.GroupLayout jPanelWrongPasswordLayout = new javax.swing.GroupLayout(jPanelWrongPassword);
        jPanelWrongPassword.setLayout(jPanelWrongPasswordLayout);
        jPanelWrongPasswordLayout.setHorizontalGroup(
            jPanelWrongPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelWrongPasswordLayout.setVerticalGroup(
            jPanelWrongPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongEmail.setBackground(new java.awt.Color(105, 105, 105));

        jLabel31.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel31.setText("Wrong Email");

        javax.swing.GroupLayout jPanelWrongEmailLayout = new javax.swing.GroupLayout(jPanelWrongEmail);
        jPanelWrongEmail.setLayout(jPanelWrongEmailLayout);
        jPanelWrongEmailLayout.setHorizontalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelWrongEmailLayout.setVerticalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongOfficeHours.setBackground(new java.awt.Color(105, 105, 105));

        jLabel40.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel40.setText("Wrong Office Hours");

        javax.swing.GroupLayout jPanelWrongOfficeHoursLayout = new javax.swing.GroupLayout(jPanelWrongOfficeHours);
        jPanelWrongOfficeHours.setLayout(jPanelWrongOfficeHoursLayout);
        jPanelWrongOfficeHoursLayout.setHorizontalGroup(
            jPanelWrongOfficeHoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongOfficeHoursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongOfficeHoursLayout.setVerticalGroup(
            jPanelWrongOfficeHoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setBackground(new java.awt.Color(105, 105, 105));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search For Employee ...!");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Name");

        jTextFieldEmployeeName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldEmployeeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmployeeName.setBorder(null);
        jTextFieldEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmployeeNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Office Hour");

        jTextFieldUserName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUserName.setBorder(null);

        jTextFieldPassword.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPassword.setBorder(null);

        jTextFieldEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setBorder(null);

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNumber.setBorder(null);

        jTextFieldAddress.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAddress.setBorder(null);
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jTextFieldOfficeHour.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldOfficeHour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldOfficeHour.setBorder(null);
        jTextFieldOfficeHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOfficeHourActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Employee ID");

        jTextFieldSearchKey.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldSearchKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSearchKey.setBorder(null);
        jTextFieldSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchKeyActionPerformed(evt);
            }
        });

        jPanelSearch.setBackground(new java.awt.Color(105, 105, 105));
        jPanelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSearchMouseExited(evt);
            }
        });

        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Find_and_Replace_48px.png"))); // NOI18N
        jLabelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearch)
                .addGap(10, 10, 10))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearch)
                .addContainerGap())
        );

        jPanelreset.setBackground(new java.awt.Color(105, 105, 105));
        jPanelreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelresetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelresetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelresetMouseExited(evt);
            }
        });

        jLabelReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_48px.png"))); // NOI18N
        jLabelReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelresetLayout = new javax.swing.GroupLayout(jPanelreset);
        jPanelreset.setLayout(jPanelresetLayout);
        jPanelresetLayout.setHorizontalGroup(
            jPanelresetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelresetLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelReset)
                .addGap(10, 10, 10))
        );
        jPanelresetLayout.setVerticalGroup(
            jPanelresetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelresetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReset)
                .addGap(10, 10, 10))
        );

        jPanelRemove.setBackground(new java.awt.Color(105, 105, 105));
        jPanelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseExited(evt);
            }
        });

        jLabelRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Trash_48px.png"))); // NOI18N
        jLabelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRemoveMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelRemoveLayout = new javax.swing.GroupLayout(jPanelRemove);
        jPanelRemove.setLayout(jPanelRemoveLayout);
        jPanelRemoveLayout.setHorizontalGroup(
            jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelRemove)
                .addGap(10, 10, 10))
        );
        jPanelRemoveLayout.setVerticalGroup(
            jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelUpdate.setBackground(new java.awt.Color(105, 105, 105));
        jPanelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelUpdateMouseExited(evt);
            }
        });

        jLabelUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Available_Updates_48px_3.png"))); // NOI18N
        jLabelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelUpdateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdateLayout = new javax.swing.GroupLayout(jPanelUpdate);
        jPanelUpdate.setLayout(jPanelUpdateLayout);
        jPanelUpdateLayout.setHorizontalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUpdate)
                .addContainerGap())
        );
        jPanelUpdateLayout.setVerticalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Search");

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Reset");

        jPanelWrongUserName1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel37.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel37.setText("Wrong User Name");

        javax.swing.GroupLayout jPanelWrongUserName1Layout = new javax.swing.GroupLayout(jPanelWrongUserName1);
        jPanelWrongUserName1.setLayout(jPanelWrongUserName1Layout);
        jPanelWrongUserName1Layout.setHorizontalGroup(
            jPanelWrongUserName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserName1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongUserName1Layout.setVerticalGroup(
            jPanelWrongUserName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongName1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel21.setText("Wrong Name");

        javax.swing.GroupLayout jPanelWrongName1Layout = new javax.swing.GroupLayout(jPanelWrongName1);
        jPanelWrongName1.setLayout(jPanelWrongName1Layout);
        jPanelWrongName1Layout.setHorizontalGroup(
            jPanelWrongName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongName1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWrongName1Layout.setVerticalGroup(
            jPanelWrongName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21)
        );

        jPanelWrongPassword1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel22.setText("Wrong Password");

        javax.swing.GroupLayout jPanelWrongPassword1Layout = new javax.swing.GroupLayout(jPanelWrongPassword1);
        jPanelWrongPassword1.setLayout(jPanelWrongPassword1Layout);
        jPanelWrongPassword1Layout.setHorizontalGroup(
            jPanelWrongPassword1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassword1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelWrongPassword1Layout.setVerticalGroup(
            jPanelWrongPassword1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongEmail1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel32.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel32.setText("Wrong Email");

        javax.swing.GroupLayout jPanelWrongEmail1Layout = new javax.swing.GroupLayout(jPanelWrongEmail1);
        jPanelWrongEmail1.setLayout(jPanelWrongEmail1Layout);
        jPanelWrongEmail1Layout.setHorizontalGroup(
            jPanelWrongEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmail1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelWrongEmail1Layout.setVerticalGroup(
            jPanelWrongEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongPhoneNo.setBackground(new java.awt.Color(105, 105, 105));

        jLabel23.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel23.setText("Wrong Phone No");

        javax.swing.GroupLayout jPanelWrongPhoneNoLayout = new javax.swing.GroupLayout(jPanelWrongPhoneNo);
        jPanelWrongPhoneNo.setLayout(jPanelWrongPhoneNoLayout);
        jPanelWrongPhoneNoLayout.setHorizontalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongPhoneNoLayout.setVerticalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongAddress.setBackground(new java.awt.Color(105, 105, 105));

        jLabel35.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel35.setText("Wrong Address");

        javax.swing.GroupLayout jPanelWrongAddressLayout = new javax.swing.GroupLayout(jPanelWrongAddress);
        jPanelWrongAddress.setLayout(jPanelWrongAddressLayout);
        jPanelWrongAddressLayout.setHorizontalGroup(
            jPanelWrongAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelWrongAddressLayout.setVerticalGroup(
            jPanelWrongAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelWrongOfficeHours1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel41.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel41.setText("Wrong Office Hours");

        javax.swing.GroupLayout jPanelWrongOfficeHours1Layout = new javax.swing.GroupLayout(jPanelWrongOfficeHours1);
        jPanelWrongOfficeHours1.setLayout(jPanelWrongOfficeHours1Layout);
        jPanelWrongOfficeHours1Layout.setHorizontalGroup(
            jPanelWrongOfficeHours1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongOfficeHours1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongOfficeHours1Layout.setVerticalGroup(
            jPanelWrongOfficeHours1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Update");

        jPanelWrongName2.setBackground(new java.awt.Color(105, 105, 105));

        jLabel24.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel24.setText("Wrong ID");

        javax.swing.GroupLayout jPanelWrongName2Layout = new javax.swing.GroupLayout(jPanelWrongName2);
        jPanelWrongName2.setLayout(jPanelWrongName2Layout);
        jPanelWrongName2Layout.setHorizontalGroup(
            jPanelWrongName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongName2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWrongName2Layout.setVerticalGroup(
            jPanelWrongName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24)
        );

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Employee ID");

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jPanelWrongName3.setBackground(new java.awt.Color(105, 105, 105));

        jLabel25.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel25.setText("Wrong ID");

        javax.swing.GroupLayout jPanelWrongName3Layout = new javax.swing.GroupLayout(jPanelWrongName3);
        jPanelWrongName3.setLayout(jPanelWrongName3Layout);
        jPanelWrongName3Layout.setHorizontalGroup(
            jPanelWrongName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongName3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWrongName3Layout.setVerticalGroup(
            jPanelWrongName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25)
        );

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldEmployeeName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanelRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(43, 43, 43)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPanelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jTextFieldOfficeHour, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelWrongName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongOfficeHours1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanelWrongName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanelreset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelWrongName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanelWrongUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelWrongEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jPanelWrongAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldOfficeHour, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)))
                    .addComponent(jPanelWrongOfficeHours1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmployeeNameActionPerformed

    private void jTextFieldOfficeHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOfficeHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOfficeHourActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchKeyActionPerformed

    private void jLabelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseClicked
        // TODO add your handling code here:
        Search();

    }//GEN-LAST:event_jLabelSearchMouseClicked

    private void jLabelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseEntered
        // TODO add your handling code here:
        setColor(jPanelSearch);
    }//GEN-LAST:event_jLabelSearchMouseEntered

    private void jLabelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseExited
        // TODO add your handling code here:
        getColor(jPanelSearch);
    }//GEN-LAST:event_jLabelSearchMouseExited

    private void jPanelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchMouseClicked
        // TODO add your handling code here:

        Search();
    }//GEN-LAST:event_jPanelSearchMouseClicked

    private void jPanelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchMouseEntered
        // TODO add your handling code here:
        setColor(jPanelSearch);
    }//GEN-LAST:event_jPanelSearchMouseEntered

    private void jPanelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchMouseExited
        // TODO add your handling code here:
        getColor(jPanelSearch);
    }//GEN-LAST:event_jPanelSearchMouseExited

    private void jLabelResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jLabelResetMouseClicked

    private void jLabelResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseEntered
        // TODO add your handling code here:
        setColor(jPanelreset);
    }//GEN-LAST:event_jLabelResetMouseEntered

    private void jLabelResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseExited
        // TODO add your handling code here:
        getColor(jPanelreset);
    }//GEN-LAST:event_jLabelResetMouseExited

    private void jPanelresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelresetMouseClicked
        // TODO add your handling code here:

        reset();

    }//GEN-LAST:event_jPanelresetMouseClicked

    private void jPanelresetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelresetMouseEntered
        // TODO add your handling code here:
        setColor(jPanelreset);
    }//GEN-LAST:event_jPanelresetMouseEntered

    private void jPanelresetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelresetMouseExited
        // TODO add your handling code here:
        getColor(jPanelreset);
    }//GEN-LAST:event_jPanelresetMouseExited

    private void jLabelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRemoveMouseClicked
        // TODO add your handling code here:
        Remove();
    }//GEN-LAST:event_jLabelRemoveMouseClicked

    private void jLabelRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRemoveMouseEntered
        // TODO add your handling code here:
        setColor(jPanelRemove);
    }//GEN-LAST:event_jLabelRemoveMouseEntered

    private void jLabelRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRemoveMouseExited
        // TODO add your handling code here:
        getColor(jPanelRemove);
    }//GEN-LAST:event_jLabelRemoveMouseExited

    private void jPanelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseClicked
        // TODO add your handling code here:
        Remove();

    }//GEN-LAST:event_jPanelRemoveMouseClicked

    private void jPanelRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseEntered
        // TODO add your handling code here:
        setColor(jPanelRemove);
    }//GEN-LAST:event_jPanelRemoveMouseEntered

    private void jPanelRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseExited
        // TODO add your handling code here:
        getColor(jPanelRemove);
    }//GEN-LAST:event_jPanelRemoveMouseExited

    private void jLabelUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateMouseClicked
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_jLabelUpdateMouseClicked

    private void jLabelUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateMouseEntered
        // TODO add your handling code here:
        setColor(jPanelUpdate);
    }//GEN-LAST:event_jLabelUpdateMouseEntered

    private void jLabelUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateMouseExited
        // TODO add your handling code here:
        getColor(jPanelUpdate);
    }//GEN-LAST:event_jLabelUpdateMouseExited

    private void jPanelUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUpdateMouseClicked
        // TODO add your handling code here:
        Update();


    }//GEN-LAST:event_jPanelUpdateMouseClicked

    private void jPanelUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUpdateMouseEntered
        // TODO add your handling code here:
        setColor(jPanelUpdate);
    }//GEN-LAST:event_jPanelUpdateMouseEntered

    private void jPanelUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUpdateMouseExited
        // TODO add your handling code here:
        getColor(jPanelUpdate);
    }//GEN-LAST:event_jPanelUpdateMouseExited

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void reset() {
        full();
        jTextFieldAddress.setText("");
        jTextFieldEmail.setText("");
        jTextFieldEmployeeName.setText("");
        jTextFieldOfficeHour.setText("");
        jTextFieldPassword.setText("");
        jTextFieldPhoneNumber.setText("");
        jTextFieldSearchKey.setText("");
        jTextFieldUserName.setText("");
        visable();
        jLabel1.setText("Search For Employee");
        editFalse();
    }

    private void setColor(JPanel p) {
        p.setBackground(new Color(0, 64, 128));
    }

    private void getColor(JPanel p) {
        p.setBackground(new Color(105, 105, 105));
    }

    public void editFalse() {
        jTextFieldSearchKey.setEditable(true);
        jTextFieldAddress.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldEmployeeName.setEditable(false);
        jTextFieldOfficeHour.setEditable(false);
        jTextFieldPassword.setEditable(false);
        jTextFieldPhoneNumber.setEditable(false);
        jTextFieldUserName.setEditable(false);
    }

    public void editTrue() {
        jTextFieldSearchKey.setEditable(false);
        jTextFieldAddress.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldEmployeeName.setEditable(true);
        jTextFieldOfficeHour.setEditable(true);
        jTextFieldPassword.setEditable(true);
        jTextFieldPhoneNumber.setEditable(true);
        jTextFieldUserName.setEditable(true);
    }

    public void full() {
        jTextFieldSearchKey.setEditable(true);
        jTextFieldAddress.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldEmployeeName.setEditable(true);
        jTextFieldOfficeHour.setEditable(true);
        jTextFieldPassword.setEditable(true);
        jTextFieldPhoneNumber.setEditable(true);
        jTextFieldUserName.setEditable(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRemove;
    private javax.swing.JLabel jLabelReset;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelUpdate;
    private javax.swing.JPanel jPanelRemove;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelUpdate;
    private javax.swing.JPanel jPanelWrongAddress;
    private javax.swing.JPanel jPanelWrongEmail;
    private javax.swing.JPanel jPanelWrongEmail1;
    private javax.swing.JPanel jPanelWrongName;
    private javax.swing.JPanel jPanelWrongName1;
    private javax.swing.JPanel jPanelWrongName2;
    private javax.swing.JPanel jPanelWrongName3;
    private javax.swing.JPanel jPanelWrongOfficeHours;
    private javax.swing.JPanel jPanelWrongOfficeHours1;
    private javax.swing.JPanel jPanelWrongPassword;
    private javax.swing.JPanel jPanelWrongPassword1;
    private javax.swing.JPanel jPanelWrongPhoneNo;
    private javax.swing.JPanel jPanelWrongUserName;
    private javax.swing.JPanel jPanelWrongUserName1;
    private javax.swing.JPanel jPanelreset;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmployeeName;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldOfficeHour;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldSearchKey;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables

    private void Update() {
        visable();
        editFalse();
        if (!jTextFieldAddress.getText().equals("") && !jTextFieldEmail.getText().equals("") && !jTextFieldEmployeeName.getText().equals("") && !jTextFieldOfficeHour.getText().equals("") && !jTextFieldPassword.getText().equals("") && !jTextFieldPhoneNumber.getText().equals("") && !jTextFieldSearchKey.getText().equals("") && !jTextFieldUserName.getText().equals("")) {
            Validation v = new Validation();
            if (v.checkID(jTextFieldSearchKey.getText())) {
                if (v.checkID(jTextFieldID.getText())) {
                    if (v.checkName(jTextFieldEmployeeName.getText())) {
                        if (v.checkUserName(jTextFieldUserName.getText())) {
                            if (v.checkPass(jTextFieldPassword.getText())) {
                                if (v.checkEmail(jTextFieldEmail.getText())) {
                                    if (v.checkPhoneNo(jTextFieldPhoneNumber.getText())) {
                                        if (v.checkAddress(jTextFieldAddress.getText())) {
                                            if (v.checkNumber(jTextFieldOfficeHour.getText())) {
                                                Employee e = new Employee();
                                                editTrue();
                                                if (!jTextFieldID.getText().equals(jTextFieldSearchKey.getText())) {
                                                if (!e.Dublicate(Integer.parseInt(jTextFieldID.getText()))) {
                                                    e = (Employee) e.get(Integer.parseInt(jTextFieldSearchKey.getText()));

                                                    if (e != null) {
                                                        e.setID(Integer.parseInt(jTextFieldID.getText()));
                                                        e.setName(jTextFieldEmployeeName.getText());
                                                        e.setUserName(jTextFieldUserName.getText());
                                                        e.setPass(jTextFieldPassword.getText());
                                                        e.setEmail(jTextFieldEmail.getText());
                                                        e.setPhoneNo(jTextFieldPhoneNumber.getText());
                                                        e.setAddress(jTextFieldAddress.getText());
                                                        if ((Integer.parseInt(jTextFieldOfficeHour.getText()) > 0) && (Integer.parseInt(jTextFieldOfficeHour.getText()) < 24)) {
                                                            e.setOfficeHour(Integer.parseInt(jTextFieldOfficeHour.getText()));

                                                            if (e.Edit(Integer.parseInt(jTextFieldSearchKey.getText()))) {
                                                                jLabel1.setText("updated successfully...!");
                                                            } else {
                                                                jLabel1.setText("not updated...!");
                                                            }
                                                        } else {
                                                            JOptionPane.showMessageDialog(null, "Not valid Office Hour Try Again :(\nHint: Ofice Hour shouid less than 24 Hour per Day.. ;)");
                                                            jPanelWrongOfficeHours.setVisible(true);
                                                        }
                                                    } else {
                                                        jLabel1.setText("Not Found Employee ...! Please, Enter Correct ID ...! :( ");
                                                        jPanelWrongName2.setVisible(true);
                                                        
                                                    }
                                                } else {
                                                    jLabel1.setText("Not Allowed New Employee ID ");
                                                    jPanelWrongName3.setVisible(true);
                                                    JOptionPane.showMessageDialog(null, "Not Allowed  Admin ID, Admin  ID is used. Please Try Again.");
                                                    editTrue();
                                                }
                                            }else{
                                                    e = (Employee) e.get(Integer.parseInt(jTextFieldSearchKey.getText()));

                                                    if (e != null) {
                                                        e.setID(Integer.parseInt(jTextFieldID.getText()));
                                                        e.setName(jTextFieldEmployeeName.getText());
                                                        e.setUserName(jTextFieldUserName.getText());
                                                        e.setPass(jTextFieldPassword.getText());
                                                        e.setEmail(jTextFieldEmail.getText());
                                                        e.setPhoneNo(jTextFieldPhoneNumber.getText());
                                                        e.setAddress(jTextFieldAddress.getText());
                                                        if ((Integer.parseInt(jTextFieldOfficeHour.getText()) > 0) && (Integer.parseInt(jTextFieldOfficeHour.getText()) < 24)) {
                                                            e.setOfficeHour(Integer.parseInt(jTextFieldOfficeHour.getText()));

                                                            if (e.Edit(Integer.parseInt(jTextFieldSearchKey.getText()))) {
                                                                jLabel1.setText("updated successfully...!");
                                                            } else {
                                                                jLabel1.setText("not updated...!");
                                                            }
                                                        } else {
                                                            JOptionPane.showMessageDialog(null, "Not valid Office Hour Try Again :(\nHint: Ofice Hour shouid less than 24 Hour per Day.. ;)");
                                                            jPanelWrongOfficeHours.setVisible(true);
                                                        }
                                                    } else {
                                                        jLabel1.setText("Not Found Employee ...! Please, Enter Correct ID ...! :( ");
                                                        jPanelWrongName2.setVisible(true);
                                                        
                                                    }
                                            }

                                            } else {

                                                JOptionPane.showMessageDialog(null, "Not valid Input for OfficeHours Try Again : ( ");

                                                jPanelWrongOfficeHours1.setVisible(true);
                                                editTrue();
                                            }
                                        } else {

                                            JOptionPane.showMessageDialog(null, "Not valid Input for Address Try Again :(");

                                            jPanelWrongAddress.setVisible(true);
                                            editTrue();
                                        }
                                    } else {

                                        JOptionPane.showMessageDialog(null, "Not valid PhoneNo Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");

                                        jPanelWrongPhoneNo.setVisible(true);
                                        editTrue();
                                    }
                                } else {

                                    JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again : ( ");

                                    jPanelWrongEmail1.setVisible(true);
                                    editTrue();
                                }
                            } else {

                                JOptionPane.showMessageDialog(null, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n ");

                                jPanelWrongPassword1.setVisible(true);
                                editTrue();
                            }
                        } else {

                            JOptionPane.showMessageDialog(null, "Not valid User Name Try Again :( ");

                            jPanelWrongUserName1.setVisible(true);
                            editTrue();
                        }
                    } else {

                        JOptionPane.showMessageDialog(null, "Not valid Name Try Again :( ");

                        jPanelWrongName1.setVisible(true);
                        editTrue();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");

                    jPanelWrongName3.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");

                jPanelWrongName2.setVisible(true);
                full();
            }

        } else {
            jLabel1.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
            editTrue();
        }
    }

    private void Remove() {
        visable();
        editFalse();
        if (!jTextFieldSearchKey.getText().equals("")) {
            Validation v = new Validation();
            if (v.checkID(jTextFieldSearchKey.getText())) {
                Employee e = new Employee();
                editTrue();
                if (e.Remove(Integer.parseInt(jTextFieldSearchKey.getText()))) {
                    jLabel1.setText("Deleted successfully...!");
                } else {
                    jLabel1.setText("not deleted...!");
                    editFalse();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                jPanelWrongName2.setVisible(true);
                editFalse();
            }
        } else {
            jLabel1.setText("Missing Required Field ... !  Please, complete before submit ...! :(");
            editFalse();
        }

    }

    private void Search() {
        visable();
        editFalse();
        if (!jTextFieldSearchKey.getText().equals("")) {
            Validation v = new Validation();
            if (v.checkID(jTextFieldSearchKey.getText())) {
                Employee e = new Employee();
                editTrue();
                if (e.SearchFor(Integer.parseInt(jTextFieldSearchKey.getText()))) {
                    jLabel1.setText("found...!");
                    Employee returned = (Employee) e.get(Integer.parseInt(jTextFieldSearchKey.getText()));
                    jTextFieldID.setText(String.valueOf(returned.getID()));
                    jTextFieldEmployeeName.setText(returned.getName());
                    jTextFieldUserName.setText(returned.getUserName());
                    jTextFieldPassword.setText(returned.getPass());
                    jTextFieldEmail.setText(returned.getEmail());
                    jTextFieldPhoneNumber.setText(returned.getPhoneNo());
                    jTextFieldAddress.setText(returned.getAddress());
                    jTextFieldOfficeHour.setText(returned.getOfficeHour() + "");
                } else {
                    jLabel1.setText("not found...!");
                    editFalse();
                    jPanelWrongName2.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                jPanelWrongName2.setVisible(true);
                editFalse();
            }

        } else {
            jLabel1.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
            editFalse();
        }

    }

    private void visable() {
        jPanelWrongUserName1.setVisible(false);
        jPanelWrongName1.setVisible(false);
        jPanelWrongPassword1.setVisible(false);
        jPanelWrongEmail1.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongAddress.setVisible(false);
        jPanelWrongOfficeHours1.setVisible(false);
        jPanelWrongName2.setVisible(false);
        jPanelWrongName3.setVisible(false);

    }
}
