/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Frame.Panel.BuyingBook;
import Frame.Panel.ListBook;
//import Frame.Panel.RentBook;
import Frame.Panel.ReturnBook;
import Frame.Panel.SearchOnlyBook;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Color;

/**
 *
 * @author DELL
 */
public class Seller_FrameOperationInBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    BuyingBook p1;
    ReturnBook p2;
    GridBagLayout layout = new GridBagLayout();
    public Seller_FrameOperationInBook() {
        initComponents();
        p1 = new BuyingBook();
        p2 = new ReturnBook();
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p1,c);
        DynamicPanel.add(p2,c);
        
        p1.setVisible(false);
        p2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BuyBook = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ListMineBook = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        BuyBook.setBackground(new java.awt.Color(0, 0, 0));
        BuyBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuyBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuyBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuyBookMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Buy_96px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BuyBookLayout = new javax.swing.GroupLayout(BuyBook);
        BuyBook.setLayout(BuyBookLayout);
        BuyBookLayout.setHorizontalGroup(
            BuyBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuyBookLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(10, 10, 10))
        );
        BuyBookLayout.setVerticalGroup(
            BuyBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyBookLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(10, 10, 10))
        );

        ListMineBook.setBackground(new java.awt.Color(0, 0, 0));
        ListMineBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListMineBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListMineBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListMineBookMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Return_Purchase_96px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ListMineBookLayout = new javax.swing.GroupLayout(ListMineBook);
        ListMineBook.setLayout(ListMineBookLayout);
        ListMineBookLayout.setHorizontalGroup(
            ListMineBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListMineBookLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(10, 10, 10))
        );
        ListMineBookLayout.setVerticalGroup(
            ListMineBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListMineBookLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(10, 10, 10))
        );

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Return Books");

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Buy Books");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BuyBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ListMineBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ListMineBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addComponent(BuyBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setBackground(new java.awt.Color(105, 105, 105));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         p1.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        ListMineBook.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        ListMineBook.setBackground(Color.black);
    }//GEN-LAST:event_jLabel3MouseExited

    private void ListMineBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMineBookMouseClicked
        // TODO add your handling code here:
         p1.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_ListMineBookMouseClicked

    private void ListMineBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMineBookMouseEntered
        // TODO add your handling code here:
        ListMineBook.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_ListMineBookMouseEntered

    private void ListMineBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMineBookMouseExited
        // TODO add your handling code here:
        ListMineBook.setBackground(Color.black);
    }//GEN-LAST:event_ListMineBookMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        BuyBook.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        BuyBook.setBackground(Color.black);
    }//GEN-LAST:event_jLabel4MouseExited

    private void BuyBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyBookMouseClicked
        // TODO add your handling code here:
         p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_BuyBookMouseClicked

    private void BuyBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyBookMouseEntered
        // TODO add your handling code here:
        BuyBook.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_BuyBookMouseEntered

    private void BuyBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyBookMouseExited
        // TODO add your handling code here:
        BuyBook.setBackground(Color.black);
    }//GEN-LAST:event_BuyBookMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuyBook;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel ListMineBook;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
